name = "sail_lean_backend"
version = "0.1.0"
keywords = ["math"]
defaultTargets = []

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
